#!/bin/bash

REGEX='({854,|{863,|{838,|{833,|{273,|{927,|{928,|{929,|{930,|{931,|{932,|{933,|{934,|{935,|{936,|{937,|{938,|{939,|{940,|{941,|{942,|{943,|{953,|{954,|{955,|{956,|{320,|{11104,|{12130,|{15010,|{15142,|{15144,|{15146,)'

if [[ -f ".checking.lua.gz" ]]; then
    rm ".checking.lua.gz"
fi

if [[ -f ".checking.lua" ]]; then
    rm ".checking.lua"
fi

# DEPRECATED LOOP FOR TESTING ALL FILES IN DIRECTORY
# for i in *.lua.gz; do
#     cp "$i" ".checking.lua.gz"

#     gunzip ".checking.lua.gz" 

#     if [[ $(grep "$REGEX" ".checking.lua") ]]; then
#         echo "Ship '$i' contains ILLEGAL BLOCKS:"

#         grep "$REGEX" ".checking.lua" --color=auto
#     fi

#     rm ".checking.lua"
# done

if [[ ! -f "$1" ]]; then
    echo "File '$1' does not exist!"
    
    exit 1
fi

cp "$1" ".checking.lua.gz"

gunzip ".checking.lua.gz" 

if [[ $(grep "$REGEX" ".checking.lua") ]]; then
    echo "Ship '$1' contains ILLEGAL BLOCKS:"

    grep "$REGEX" ".checking.lua" --color=auto
else
    echo "Ship '$1' is good!"
fi

rm ".checking.lua"
